apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: sample-default
  namespace: default
spec:
  destination:
    name: sample-svc
  precedence: 1
  route:
  - labels:
      version: v1
    weight: 90
  - labels:
      version: v2
    weight: 10