apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: httpbin-timeout
spec:
  destination:
    name: sample-svc
  route:
  httpReqTimeout:
    simpleTimeout:
      timeout: 10s